- name: tmux config is overlaid with local config
  template:
    src: tmux.local
    dest: ~/.tmux.local
    mode: 0644
  become: true
  become_user: suhlig
  tags: tmux
- name: Hardware watchdog is enabled # https://raspberrypi.stackexchange.com/a/113193
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: "{{item.regex}}"
    line: "{{item.replace_with}}"
  with_items:
    - regex: ^RuntimeWatchdogSec=
      replace_with: RuntimeWatchdogSec=12s
    - regex: ^DefaultTimeoutStopSec=
      replace_with: DefaultTimeoutStopSec=10
    - regex: ^RebootWatchdogSec=
      replace_with: RebootWatchdogSec=2min
  become: true
  tags: [ hardware, watchdog ]
- name: RAM is the log target
  apt:
    update_cache: yes
    name: [ log2ram ]
  tags: [ apt, software, log, ram ]
