# map ansible_facts['architecture'] to the architecture part of the download URL
deb_architectures:
  armv6l: armv6
  armv7l: armv7
  aarch64: arm64v8
  x86_64: amd64
mediamtx_tag: v1.8.2 # get one from https://github.com/bluenviron/mediamtx/releases
rpiCameraCamID: 0
rpiCameraWidth: 1920
rpiCameraHeight: 1080
rpiCameraHFlip: false
rpiCameraVFlip: false
rpiCameraBrightness: 0
rpiCameraContrast: 1
rpiCameraSaturation: 1
rpiCameraSharpness: 1
rpiCameraExposure: normal
rpiCameraAWB: auto
rpiCameraAWBGains: [0, 0]
rpiCameraDenoise: "off"
rpiCameraShutter: 0
rpiCameraMetering: centre
rpiCameraGain: 0
rpiCameraEV: 0
rpiCameraROI:
rpiCameraHDR: false
rpiCameraTuningFile:
rpiCameraMode:
rpiCameraFPS: 30
rpiCameraIDRPeriod: 60
rpiCameraBitrate: 1000000
rpiCameraProfile: main
rpiCameraLevel: "4.1"
rpiCameraAfMode: continuous
rpiCameraAfRange: normal
rpiCameraAfSpeed: normal
rpiCameraLensPosition: 0.0
rpiCameraAfWindow:
rpiCameraTextOverlayEnable: false
rpiCameraTextOverlay: "%Y-%m-%d %H:%M:%S - MediaMTX"
