# General-purpose data compression with high compression ratio
brew "xz"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Download with resuming and segmented downloading
brew "aria2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Bash Automated Testing System
brew "bats-core"
# Cross platform file encryption utility using blowfish
brew "bcrypt"
# Remove large files or passwords from Git history like git-filter-branch
brew "bfg"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# Fish completion for brew-cask
brew "brew-cask-completion"
# Crop PDF files
brew "briss"
# Bash completion for Bundler
brew "bundler-completion"
# Powerful, enterprise-ready, open source web server with automatic HTTPS
brew "caddy"
# Ruby environment tool
brew "chruby"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Open source multi-tool for exploring and publishing data
brew "datasette"
# Load/unload environment variables based on $PWD
brew "direnv"
# Convert ASCII diagrams into proper bitmap graphics
brew "ditaa"
# Tool for exploring each layer in a docker image
brew "dive"
# Convert text between DOS, UNIX, and Mac formats
brew "dos2unix"
# Run arbitrary commands when files change
brew "entr"
# Modern replacement for 'ls'
brew "exa"
# CLI tool for quick access to files and directories
brew "fasd"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# Command-line fuzzy finder written in Go
brew "fzf"
# Bash completion for gem
brew "gem-completion"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Git extension to generate reports for standup meetings
brew "git-standup"
# Blazing fast terminal-ui for git written in rust
brew "gitui"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Deliver Go binaries as fast and easily as possible
brew "goreleaser"
# General-purpose preprocessor with customizable syntax
brew "gpp"
# Image processing tools collection
brew "graphicsmagick"
# Colorize logfiles and command output
brew "grc"
# GitHub Markdown previewer
brew "grip"
# Command-line interface for Hetzner Cloud
brew "hcloud"
# Convert source code to formatted text with syntax highlighting
brew "highlight"
# <hr />, for your terminal window
brew "hr"
# Improved top (interactive process viewer)
brew "htop"
# Spell checker and morphological analyzer
brew "hunspell"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# CLI wrapper for basic network utilities on macOS - ip command
brew "iproute2mac"
# Serializes the output of command-line tools to structured JSON output
brew "jc"
# JSON output from a shell
brew "jo"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Input filter for the pager less
brew "lesspipe"
# Mac App Store command-line interface
brew "mas"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Parses Message Sequence Chart descriptions and produces images
brew "mscgen"
# SMTP client that can be used as an SMTP plugin for Mutt
brew "msmtp"
# NCurses Disk Usage
brew "ncdu"
# Trigger notifications when a process completes
brew "noti"
# Bash completion for open
brew "open-completion"
# Swiss-army knife of markup format conversion
brew "pandoc"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Search PDFs for strings matching a regular expression
brew "pdfgrep"
# Display the PID number for a given process name
brew "pidof"
# Professional collaborative platform for embedded development
brew "platformio"
# Tool for managing OCI containers and pods
brew "podman"
# Create large posters out of PostScript pages
brew "poster"
# Object-relational database system
brew "postgresql@14"
# Convert bitmaps to vector graphics
brew "potrace"
# Show ps output as a tree
brew "pstree"
# Monitor data's progress through a pipe
brew "pv"
# Transfer files to and from your computer by scanning a QR code
brew "qrcp"
# Bash completion for Rake
brew "rake-completion"
# Rsync for cloud storage
brew "rclone"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Wrapper around ripgrep that adds multiple rich file types
brew "ripgrep-all"
# Text replacement utility
brew "rpl"
# Bash completion for Ruby
brew "ruby-completion"
# Install Ruby, JRuby, Rubinius, TruffleRuby, or mruby
brew "ruby-install"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Zsh prompt for Astronauts
brew "spaceship"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Add a public key to a remote machine's authorized_keys file
brew "ssh-copy-id", link: true
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Easiest, most secure way to use WireGuard and 2FA
brew "tailscale"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Tool for writing command-line pipes with instant live preview
brew "up"
# Bash completion for Vagrant
brew "vagrant-completion"
# Vi 'workalike' with many additional features
brew "vim"
# Image processing library
brew "vips"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Execute commands when watched files change
brew "watchexec"
# Internet file retriever
brew "wget"
# Process YAML documents from the CLI
brew "yq"
# Fork of youtube-dl with additional features and fixes
brew "yt-dlp"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Cross-platform Text Expander written in Rust
brew "federico-terzi/espanso/espanso"
# Pairing tool for Git
brew "git-duet/tap/git-duet"
# δyƒƒ /ˈdʏf/ - A diff tool for YAML files, and sometimes JSON
brew "homeport/tap/dyff"
# /ˈheɪvənə/ - Think of it as a swiss army knife for Kubernetes tasks
brew "homeport/tap/havener"
# macOS command line utility to configure multi-display resolutions and arrangements. Essentially XRandR for macOS.
brew "jakehilborn/jakehilborn/displayplacer"
# Common assertions for Bats
brew "kaos/shell/bats-assert"
# TOTP cli backed by the OS X keychain
brew "moul/moul/totp-keychain"
# 3DxWare Driver
cask "3dconnexion"
# GPU-accelerated terminal emulator
cask "alacritty"
# Audio video conferencing
cask "alfaview"
# Application launcher and productivity software
cask "alfred"
# Enable Windows-like alt-tab
cask "alt-tab"
# Multi-cloud backup application
cask "arq"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Desktop password and login vault
cask "bitwarden"
# Server and cloud storage browser
cask "cyberduck"
# Visually compare and merge files
cask "diffmerge"
# Disk usage utility
cask "disk-inventory-x"
# Application window manager focusing on simplicity
cask "divvy"
# App to build and share containerized applications and microservices
cask "docker"
# GIT client
cask "fork"
# Scan software for Fujitsu document scanners
cask "fujitsu-scansnap-manager"
# Web browser
cask "google-chrome"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Desktop automation application
cask "hammerspoon"
# Command-line API client
cask "ibm-cloud-cli"
# Terminal emulator as alternative to Apple's Terminal app
# Create, manage and debug system- and user services
cask "launchcontrol"
# Email tracker, read receipt and spy pixel blocker plugin for Apple Mail
cask "mailtrackerblocker"
# Visual diff and merge tool
cask "meld"
# German banking and financial management software
cask "moneymoney"
cask "obs-virtualcam"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# QuickLook generator for Markdown files
cask "qlmarkdown"
cask "qlprettypatch"
# QuickLook plugin for plaintext files without an extension
cask "qlstephen"
# QuickLook generator for video files
cask "qlvideo"
# QuickLook plugin for CSV files
cask "quicklook-csv"
# QuickLook plugin for JSON files
cask "quicklook-json"
# QuickLook generator for Adobe Swatch Exchange files
cask "quicklookase"
cask "scansnap-manager-s1500"
# Instant messaging application focusing on security
cask "signal"
# 3D design software
cask "sketchup"
# Team communication and collaboration software
cask "slack"
# System monitor for the menu bar
cask "stats"
# Application for inspecting installer packages
cask "suspicious-package"
# Multi-platform VNC client and server
cask "tigervnc-viewer"
# PKG software package uninstall tool
cask "uninstallpkg"
# Development environment
cask "vagrant"
cask "vagrant-manager"
# Tool to hide menu bar icons
cask "vanilla"
# Virtualizer for x86 hardware
cask "virtualbox"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Remote desktop application focusing on security
cask "vnc-viewer"
cask "webpquicklook"
# View output from scripts in the menu bar
cask "xbar"
mas "Drafts", id: 1435957248
mas "EasyMQTT", id: 1523099606
mas "Soulver 2", id: 413965349
mas "Tailscale", id: 1475387142
