namespace: suhlig
name: foundation
version: 1.1.4
readme: README.md
authors: [ Steffen Uhlig <steffen@familie-uhlig.net> ]
license: [ MIT ]
dependencies: { thorian93.main: ">=1.1.0" }
repository: https://github.com/suhlig/foundation
