namespace: suhlig
name: foundation
version: 1.1.0
readme: README.md
authors:
  - Steffen Uhlig <steffen@familie-uhlig.net>
license:
  - MIT
tags: []
dependencies:
  thorian93.main: ">=0.0.2"
repository: https://github.com/suhlig/foundation
