galaxy_info:
  role_name: speedtest
  description: Install Ookla Speedtest CLI
  author: Steffen Uhlig <steffen@familie-uhlig.net>
  license: MIT
  min_ansible_version: "2.6"
  platforms:
    - name: Debian
      versions:
        - [ 11, 12 ]
    - name: Ubuntu
      versions:
        - all
