galaxy_info:
  role_name: main
  description: Apply main configuration
  author: Steffen Uhlig <steffen@familie-uhlig.net>
  license: MIT
  min_ansible_version: "2.6"
  platforms:
    - name: Debian
      versions:
        - [ 11, 12 ]
    - name: Ubuntu
      versions:
        - all
dependencies:
  - role: suhlig.foundation.minimal
    become: true
    tags: [ suhlig ]
