---
# The Go package name to build; either local (e.g. "./golden-egg") or fully qualified (e.g. "github.com/nowak-reisen/pile/golden-egg")
konsible_package: "./app"
# The name of the container and the prefix for Traefik labels
konsible_app_name: "app"
# The platform to build for
konsible_platform: "linux/arm64"
# The port the app listens on inside the container
konsible_port: "8080"
# The domain for the Traefik router
konsible_domain: "{{ domain }}"
