galaxy_info:
  role_name: minimal
  description: Apply minimal configuration
  author: Steffen Uhlig <steffen@familie-uhlig.net>
  license: MIT
  min_ansible_version: "2.6"
  platforms:
    - name: Debian
      versions:
        - [ 11, 12 ]
    - name: Ubuntu
      versions:
        - all
dependencies:
  - role: thorian93.main.journald
    vars: { journald_stable_os: [ Ubuntu 24, Debian 12 ] }
    become: yes
    tags: [ system, journald ]
  - role: thorian93.main.common
    vars:
      common_configure_timezone: true
      common_timezone: Europe/Berlin
      common_stable_os: [ Ubuntu 24, Debian 12 ]
    become: yes
    tags: [ system, timezone ]
  - role: thorian93.main.ntp
    vars: { ntp_stable_os: [ Ubuntu 24, Debian 12 ] }
    become: yes
    tags: [ system, ntp ]
