- name: Prerequisite software is installed
  ansible.builtin.apt:
    update_cache: yes
    name: [ acl, starship, stow ]
  tags: [ apt, software, acl ]
- name: dotfiles repo is cloned and up-to-date
  ansible.builtin.git:
    repo: https://github.com/suhlig/dotfiles
    dest: ~/.dotfiles
  environment: { GIT_CONFIG_GLOBAL: /dev/null }
  become: true
  become_user: suhlig
  tags: [git, dotfiles]
- name: Unwanted default dotfiles are not present
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/.profile
    - ~/.bashrc
    - ~/.zshrc
    - ~/.tmux.conf # override the one from suhlig.foundation.minimal
    - ~/.hushlogin # may be there from suhlig.foundation.local_user
  become: true
  become_user: suhlig
  tags: [dotfiles, profile]
- name: dotfiles are bootstrapped
  ansible.builtin.shell: ./bootstrap.zsh
  args:
    chdir: ~/.dotfiles
    creates: ~/.zsh_plugins.txt
  become: true
  become_user: suhlig
  tags: [dotfiles, stow]
- name: tmux tpm plugin is cloned and up-to-date
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  environment:
    GIT_CONFIG_GLOBAL: /dev/null
  become: true
  become_user: suhlig
  tags: [git, dotfiles, plugin]
