- name: oh-my-zsh repo is cloned and up-to-date
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
  environment:
    GIT_CONFIG_GLOBAL: /dev/null # prevent use of "git.insteadof https" from global config
  become: true
  become_user: suhlig
  tags: git, dotfiles, ohmyzsh
- name: dotfiles repo is cloned and up-to-date
  git:
    repo: https://github.com/suhlig/dotfiles
    dest: ~/.dotfiles
  environment:
    GIT_CONFIG_GLOBAL: /dev/null
  become: true
  become_user: suhlig
  tags: [git, dotfiles]
- name: Unwanted default dotfiles are not present
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/.profile
    - ~/.bashrc
    - ~/.zshrc
    - ~/.tmux.conf # override the one from suhlig.foundation.minimal
    - ~/.hushlogin # may be there from suhlig.foundation.local_user
  become: true
  become_user: suhlig
  tags: [dotfiles, profile]
- name: dotfiles are stowed
  command: stow common linux
  args: { chdir: ~/.dotfiles }
  become: true
  become_user: suhlig
  tags: [dotfiles, stow]
- name: oh-my-zsh autoupdate plugin is cloned and up-to-date
  git:
    repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
    dest: ~/.oh-my-zsh/custom/plugins/autoupdate
  environment:
    GIT_CONFIG_GLOBAL: /dev/null
  become: true
  become_user: suhlig
  tags: [git, dotfiles, ohmyzsh, plugin]
- name: zsh-vi-mode plugin is cloned and up-to-date
  git:
    repo: https://github.com/jeffreytse/zsh-vi-mode
    dest: ~/.oh-my-zsh/custom/plugins/zsh-vi-mode
  environment:
    GIT_CONFIG_GLOBAL: /dev/null
  become: true
  become_user: suhlig
  tags: [git, dotfiles, ohmyzsh, plugin]
- name: zsh-syntax-highlighting plugin is cloned and up-to-date
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  environment:
    GIT_CONFIG_GLOBAL: /dev/null
  become: true
  become_user: suhlig
  tags: [git, dotfiles, ohmyzsh, plugin]
- name: zsh-autosuggestions plugin is cloned and up-to-date
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  environment:
    GIT_CONFIG_GLOBAL: /dev/null
  become: true
  become_user: suhlig
  tags: [git, dotfiles, ohmyzsh, plugin]
- name: tmux tpm plugin is cloned and up-to-date
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  environment:
    GIT_CONFIG_GLOBAL: /dev/null
  become: true
  become_user: suhlig
  tags: [git, dotfiles, ohmyzsh, plugin]
