- name: User "{{ local_user.name }}" exists
  ansible.builtin.user:
    name: "{{ local_user.name }}"
    comment: "{{ local_user.comment }}"
    state: present
  become: true
  tags: [ folders ]
- name: Passwordless sudo is enabled for "{{ local_user.name }}"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ local_user.name }}"
    content: "{{ local_user.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  become: true
  tags: [ sudo, su, password ]
