- name: Software is installed
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apt-transport-https
#      - software-properties-common # Not needed on Debian 13 anymore
      - aptitude # required for upgrade mode 'full'
      - sudo
  tags: [apt, software]
- name: Software is fully upgraded
  ansible.builtin.apt:
    upgrade: full
  tags: [apt, upgrade]
- name: Preferred locale exists
  ansible.builtin.locale_gen:
    name: en_US.UTF-8
    state: present
  tags: [l10n, i18n, locale]
